// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package policy

import (
	rbacv1 "k8s.io/api/rbac/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var SigstoreWebhookCR = &rbacv1.ClusterRole{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "sigstore",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "policy-controller",
			"app.kubernetes.io/version":    "0.8.0",
			"control-plane":                "sigstore-policy-controller-webhook",
			"helm.sh/chart":                "policy-controller-0.6.0",
		},
		Name: "sigstore-policy-controller-webhook",
	},
	Rules: []rbacv1.PolicyRule{
		{
			APIGroups: []string{""},
			Resources: []string{"events"},
			Verbs:     []string{"create", "patch"},
		}, {
			APIGroups: []string{"admissionregistration.k8s.io"},
			Resources: []string{
				"validatingwebhookconfigurations",
				"mutatingwebhookconfigurations",
			},
			Verbs: []string{"list", "watch"},
		}, {
			APIGroups: []string{"admissionregistration.k8s.io"},
			ResourceNames: []string{
				"policy.sigstore.dev",
				"defaulting.clusterimagepolicy.sigstore.dev",
				"validating.clusterimagepolicy.sigstore.dev",
			},
			Resources: []string{
				"validatingwebhookconfigurations",
				"mutatingwebhookconfigurations",
			},
			Verbs: []string{"get", "update", "delete"},
		}, {
			APIGroups:     []string{""},
			ResourceNames: []string{"sigstore"},
			Resources:     []string{"namespaces"},
			Verbs:         []string{"get", "list"},
		}, {
			APIGroups:     []string{""},
			ResourceNames: []string{"sigstore"},
			Resources:     []string{"namespaces/finalizers"},
			Verbs:         []string{"update"},
		}, {
			APIGroups: []string{""},
			Resources: []string{"serviceaccounts", "secrets"},
			Verbs:     []string{"get"},
		}, {
			APIGroups: []string{"policy.sigstore.dev"},
			Resources: []string{
				"clusterimagepolicies",
				"clusterimagepolicies/status",
			},
			Verbs: []string{"get", "list", "update", "watch", "patch"},
		}, {
			APIGroups: []string{"apiextensions.k8s.io"},
			Resources: []string{"customresourcedefinitions"},
			Verbs:     []string{"get", "list", "watch", "update"},
		}, {
			APIGroups:     []string{"apiextensions.k8s.io"},
			ResourceNames: []string{"trustroots.policy.sigstore.dev"},
			Resources:     []string{"customresourcedefinitions"},
			Verbs:         []string{"get", "update", "list"},
		}, {
			APIGroups: []string{"policy.sigstore.dev"},
			Resources: []string{"trustroots", "trustroots/status"},
			Verbs:     []string{"get", "list", "update", "watch", "patch"},
		},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "rbac.authorization.k8s.io/v1",
		Kind:       "ClusterRole",
	},
}
