// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package policy

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

var SigstoreWebhookMetricsSVC = &corev1.Service{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "sigstore",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "policy-controller",
			"app.kubernetes.io/version":    "0.8.0",
			"control-plane":                "sigstore-policy-controller-webhook",
			"helm.sh/chart":                "policy-controller-0.6.0",
		},
		Name:      "sigstore-policy-controller-webhook-metrics",
		Namespace: "sigstore",
	},
	Spec: corev1.ServiceSpec{
		Ports: []corev1.ServicePort{
			{
				Name:     "metrics",
				Port:     int32(9090),
				Protocol: corev1.Protocol("TCP"),
				TargetPort: intstr.IntOrString{
					StrVal: "metrics",
					Type:   intstr.Type(int64(1)),
				},
			},
		},
		Selector: map[string]string{
			"app.kubernetes.io/instance": "sigstore",
			"app.kubernetes.io/name":     "policy-controller",
			"control-plane":              "sigstore-policy-controller-webhook",
		},
		Type: corev1.ServiceType("ClusterIP"),
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "Service",
	},
}

var WebhookSVC = &corev1.Service{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "sigstore",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "policy-controller",
			"app.kubernetes.io/version":    "0.8.0",
			"control-plane":                "sigstore-policy-controller-webhook",
			"helm.sh/chart":                "policy-controller-0.6.0",
		},
		Name:      "webhook",
		Namespace: "sigstore",
	},
	Spec: corev1.ServiceSpec{
		Ports: []corev1.ServicePort{
			{
				Name:     "https",
				Port:     int32(443),
				Protocol: corev1.Protocol("TCP"),
				TargetPort: intstr.IntOrString{
					StrVal: "https",
					Type:   intstr.Type(int64(1)),
				},
			},
		},
		Selector: map[string]string{
			"app.kubernetes.io/instance": "sigstore",
			"app.kubernetes.io/name":     "policy-controller",
			"control-plane":              "sigstore-policy-controller-webhook",
		},
		Type: corev1.ServiceType("ClusterIP"),
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "Service",
	},
}
