// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package keda

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiregistrationv1 "k8s.io/kube-aggregator/pkg/apis/apiregistration/v1"
)

var V1Beta1ExternalMetricsK8SIoApiservices = &apiregistrationv1.APIService{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/component":  "operator",
			"app.kubernetes.io/instance":   "keda",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "v1beta1.external.metrics.k8s.io",
			"app.kubernetes.io/part-of":    "keda-operator",
			"app.kubernetes.io/version":    "2.11.1",
			"helm.sh/chart":                "keda-2.11.1",
		},
		Name: "v1beta1.external.metrics.k8s.io",
	},
	Spec: apiregistrationv1.APIServiceSpec{
		Group:                "external.metrics.k8s.io",
		GroupPriorityMinimum: int32(100),
		Service: &apiregistrationv1.ServiceReference{
			Name:      "keda-operator-metrics-apiserver",
			Namespace: "keda",
			Port:      P(int32(443)),
		},
		Version:         "v1beta1",
		VersionPriority: int32(100),
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "apiregistration.k8s.io/v1",
		Kind:       "APIService",
	},
}
