// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package vmk8s

// var VMSA = &corev1.ServiceAccount{
// 	ObjectMeta: metav1.ObjectMeta{
// 		Labels: map[string]string{
// 			"app.kubernetes.io/instance":   "vmk8s",
// 			"app.kubernetes.io/managed-by": "Helm",
// 			"app.kubernetes.io/name":       "victoria-metrics-k8s-stack",
// 			"app.kubernetes.io/version":    "v1.91.2",
// 			"helm.sh/chart":                "victoria-metrics-k8s-stack-0.16.3",
// 		},
// 		Name: "vmk8s-victoria-metrics-k8s-stack",
// 	},
// 	TypeMeta: metav1.TypeMeta{
// 		APIVersion: "v1",
// 		Kind:       "ServiceAccount",
// 	},
// }
