// Copyright (c) 2023 Volvo Car Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package ksm

import (
	v1 "github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var KsmServiceMonitor = &v1.ServiceMonitor{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/component":  "metrics",
			"app.kubernetes.io/instance":   "ksm",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "kube-state-metrics",
			"app.kubernetes.io/part-of":    "kube-state-metrics",
			"app.kubernetes.io/version":    "2.9.2",
			"helm.sh/chart":                "kube-state-metrics-5.8.1",
		},
		Name:      "ksm-kube-state-metrics",
		Namespace: "monitoring",
	},
	Spec: v1.ServiceMonitorSpec{
		Endpoints: []v1.Endpoint{{Port: "http"}},
		JobLabel:  "app.kubernetes.io/name",
		Selector: metav1.LabelSelector{MatchLabels: map[string]string{
			"app.kubernetes.io/instance": "ksm",
			"app.kubernetes.io/name":     "kube-state-metrics",
		}},
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "monitoring.coreos.com/v1",
		Kind:       "ServiceMonitor",
	},
}
