// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package dragonflydb

import (
	"context"
	"errors"
	"os"
	"os/exec"

	certmanagerv1 "github.com/cert-manager/cert-manager/pkg/apis/certmanager/v1"
	"github.com/volvo-cars/lingon/pkg/kube"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
)

// validate the struct implements the interface
var _ kube.Exporter = (*Dragonflydb)(nil)

// Dragonflydb contains kubernetes manifests
type Dragonflydb struct {
	kube.App

	Certificate *certmanagerv1.Certificate
	Deploy      *appsv1.Deployment
	MetricsSVC  *corev1.Service
	SA          *corev1.ServiceAccount
	SVC         *corev1.Service
}

// New creates a new Dragonflydb
func New() *Dragonflydb {
	return &Dragonflydb{
		Certificate: Certificate,
		Deploy:      Deploy,
		MetricsSVC:  MetricsSVC,
		SA:          SA,
		SVC:         SVC,
	}
}

// Apply applies the kubernetes objects to the cluster
func (a *Dragonflydb) Apply(ctx context.Context) error {
	return Apply(ctx, a)
}

// Export exports the kubernetes objects to YAML files in the given directory
func (a *Dragonflydb) Export(dir string) error {
	return kube.Export(a, kube.WithExportOutputDirectory(dir))
}

// Apply applies the kubernetes objects contained in Exporter to the cluster
func Apply(ctx context.Context, km kube.Exporter) error {
	cmd := exec.CommandContext(ctx, "kubectl", "apply", "-f", "-")
	cmd.Env = os.Environ()        // inherit environment in case we need to use kubectl from a container
	stdin, err := cmd.StdinPipe() // pipe to pass data to kubectl
	if err != nil {
		return err
	}

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	go func() {
		defer func() {
			err = errors.Join(err, stdin.Close())
		}()
		if errEW := kube.Export(
			km,
			kube.WithExportWriter(stdin),
			kube.WithExportAsSingleFile("stdin"),
		); errEW != nil {
			err = errors.Join(err, errEW)
		}
	}()

	if errS := cmd.Start(); errS != nil {
		return errors.Join(err, errS)
	}

	// waits for the command to exit and waits for any copying
	// to stdin or copying from stdout or stderr to complete
	return errors.Join(err, cmd.Wait())
}

// P converts T to *T, useful for basic types
func P[T any](t T) *T {
	return &t
}
