// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package dragonflydb

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

var SA = &corev1.ServiceAccount{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "dragonflydb",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "dragonfly",
			"app.kubernetes.io/version":    "v1.6.1",
			"helm.sh/chart":                "dragonfly-v1.6.1",
		},
		Name:      "dragonflydb",
		Namespace: "dragonflydb",
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "ServiceAccount",
	},
}
