// Code generated by lingon. EDIT AS MUCH AS YOU LIKE.

package dragonflydb

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
)

var MetricsSVC = &corev1.Service{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "dragonflydb",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "dragonfly",
			"app.kubernetes.io/version":    "v1.6.1",
			"helm.sh/chart":                "dragonfly-v1.6.1",
			"type":                         "metrics",
		},
		Name:      "dragonflydb-metrics",
		Namespace: "dragonflydb",
	},
	Spec: corev1.ServiceSpec{
		Ports: []corev1.ServicePort{
			{
				Name:       "metrics",
				Port:       int32(6379),
				Protocol:   corev1.Protocol("TCP"),
				TargetPort: intstr.IntOrString{IntVal: int32(6379)},
			},
		},
		Selector: map[string]string{
			"app.kubernetes.io/instance": "dragonflydb",
			"app.kubernetes.io/name":     "dragonfly",
		},
		Type: corev1.ServiceType("ClusterIP"),
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "Service",
	},
}

var SVC = &corev1.Service{
	ObjectMeta: metav1.ObjectMeta{
		Labels: map[string]string{
			"app.kubernetes.io/instance":   "dragonflydb",
			"app.kubernetes.io/managed-by": "Helm",
			"app.kubernetes.io/name":       "dragonfly",
			"app.kubernetes.io/version":    "v1.6.1",
			"helm.sh/chart":                "dragonfly-v1.6.1",
		},
		Name:      "dragonflydb",
		Namespace: "dragonflydb",
	},
	Spec: corev1.ServiceSpec{
		Ports: []corev1.ServicePort{
			{
				Name:     "dragonfly",
				Port:     int32(6379),
				Protocol: corev1.Protocol("TCP"),
				TargetPort: intstr.IntOrString{
					StrVal: "dragonfly",
					Type:   intstr.Type(int64(1)),
				},
			},
		},
		Selector: map[string]string{
			"app.kubernetes.io/instance": "dragonflydb",
			"app.kubernetes.io/name":     "dragonfly",
		},
		Type: corev1.ServiceType("ClusterIP"),
	},
	TypeMeta: metav1.TypeMeta{
		APIVersion: "v1",
		Kind:       "Service",
	},
}
