---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-nats-volvocars-com-v1-stream
  failurePolicy: Fail
  name: mstream.kb.io
  rules:
  - apiGroups:
    - nope.volvocars.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-nats-volvocars-com-v1-stream
  failurePolicy: Fail
  name: vstream.kb.io
  rules:
  - apiGroups:
    - nope.volvocars.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - streams
  sideEffects: None
