---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - nope.volvocars.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nope.volvocars.com
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - consumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nope.volvocars.com
  resources:
  - consumers/finalizers
  verbs:
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - consumers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - streams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nope.volvocars.com
  resources:
  - streams/finalizers
  verbs:
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - streams/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nope.volvocars.com
  resources:
  - users/finalizers
  verbs:
  - update
- apiGroups:
  - nope.volvocars.com
  resources:
  - users/status
  verbs:
  - get
  - patch
  - update
