# Copyright (c) 2023 Volvo Car Corporation
# SPDX-License-Identifier: Apache-2.0

# permissions for end users to view streams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: stream-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nope
    app.kubernetes.io/part-of: nope
    app.kubernetes.io/managed-by: kustomize
  name: stream-viewer-role
rules:
- apiGroups:
  - nope.volvocars.com
  resources:
  - streams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nope.volvocars.com
  resources:
  - streams/status
  verbs:
  - get
