name: Black Duck Pro
on:
  pull_request:
    branches:
      - master
  schedule:
    # Every Monday at 08:00
    - cron: "0 08 * * 1"
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

      - name: Set up Java 11
        uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Run Synopsys Detect
        uses: synopsys-sig/detect-action@58681e147f1b8c409be0c44bc22a6f4fd8b40244 # v0.3.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}